name: Deploy Frontend
on:
  push:
    branches:
      - main
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setting up containers
        run: docker-compose up --build -d

      - name: Installing dependencies
        run: docker-compose exec -T app composer install

      - name: Running migrations
        run: docker-compose exec -T app php bin/console doctrine:migrations:migrate --no-interaction --env test

      - name: Running fixtures
        run: docker-compose exec -T app php bin/console doctrine:fixtures:load --no-interaction --env test

      - name: Running tests
        run: docker-compose exec -T app php bin/phpunit
 
      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'
 
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: rca-symfony
          environment_name: Rcasymfony-env
          existing_bucket_name: elasticbeanstalk-us-west-2-361267194583
          region: us-west-2
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip